<?php
/**
 * @file
 * Code for the Cluster Alert feature.
 */

include_once 'cluster_alert.features.inc';

/**
 * Implements hook_node_insert().
 */
function cluster_alert_node_insert($node) {
  if ($node->type !== 'alert' || $node->status !== NODE_PUBLISHED)
    return;

  $wrapper = entity_metadata_wrapper('node', $node);
  $group_ids = ClusterAPI_Type::getReferenceIds('node', $node, 'og_group_ref', TRUE);

  foreach ($group_ids as $gid) {
    $plain_text_body = trim(strip_tags(text_summary($wrapper->body->value()['value'])));
    cluster_api_push($gid, $node->title, $plain_text_body, ['type' => 'new_alert', 'group_id' => $gid]);
  }
}

/**
 * Implements hook_node_update().
 */
function cluster_alert_node_update($node) {
  cluster_alert_node_insert($node);
}
