<?php
/**
 * @file
 * Code for the cluster_docs feature.
 */

include_once 'cluster_docs.features.inc';
include_once 'cluster_docs.admin.inc';
include_once 'cluster_docs.pathauto.inc';

const CLUSTER_DOCS_PER_PAGE = 5;

/**
 *  Implements hook_menu().
 */
function cluster_docs_menu() {
  $items['node/%/documents'] = array(
    'title' => 'Documents',
    'page callback' => 'cluster_docs_all',
    'page arguments' => array(1),
    'access callback' => 'og_is_group',
    'access arguments' => array(0, 1),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Page callback, shows a group's documents using Search API.
 * @param $nid
 * @return Render array
 */
function cluster_docs_all($nid) {
  global $language;
  $query = search_api_query('default_node_index', array(
    'languages' => array($language->language),
  ));

  $filter = $query->createFilter();
  $filter->condition('og_group_ref', $nid);
  $filter->condition('type', 'document');
  $query->filter($filter);

  $offset = pager_find_page() * CLUSTER_DOCS_PER_PAGE;
  $query->range($offset, CLUSTER_DOCS_PER_PAGE);

  $results = $query->execute();

  pager_default_initialize($results['result count'], CLUSTER_DOCS_PER_PAGE);

  $nids = array_keys($results['results']);

  $ret = GroupPageContent::getList($nids, 'teaser', 'cluster_docs_all');
  $ret['pager'] = array(
    '#theme' => 'pager',
  );

  return $ret;
}

/**
 *  Get all key docs for a group, grouped by category.
 * @param $gid
 *  Group node id.
 * @return
 *  array of node ids for document nodes keyed by category vocabulary machine name, or FALSE if no matching result.
 */
function cluster_docs_get_grouped_key_docs($gid) {
  $query = new EntityFieldQuery();
  $res = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'document')
    ->fieldCondition('og_group_ref', 'target_id', $gid)
    ->fieldCondition('field_key_document', 'value', 1)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->execute();

  if (!isset($res['node'])) {
    return FALSE;
  }

  $documents = entity_load('node', array_keys($res['node']));
}

/**
 * Implements hook_theme().
 */
function cluster_docs_theme() {
  return array(
    'cluster_docs_all' => array(
      'file' => 'theme/cluster_docs.theme.inc',
      'render element' => 'element',
    ),
    'cluster_docs_cards' => array(
      'file' => 'theme/cluster_docs.theme.inc',
      'variables' => array(
        'category' => '',
        'nodes' => array(),
      ),
      'template' => 'theme/cluster_docs_cards'
    ),
  );
}
