<?php
/**
 * @file
 * cluster_docs.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function cluster_docs_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Recovery',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '000017a9-c455-4f57-860d-00447f88d1d2',
    'vocabulary_machine_name' => 'response_phase',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Recovery',
          'format' => NULL,
          'safe_value' => 'Recovery',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Recovery',
          'format' => NULL,
          'safe_value' => 'Recovery',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Recovery',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 22,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562601,
          'changed' => 1422562601,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Cluster Evaluation',
    'description' => 'An evaluative review of the work done by the cluster and the coordination teams',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '003e9b3b-2eab-4384-9221-1d17b7eaf418',
    'vocabulary_machine_name' => 'assessment_monitoring_evaluation',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Cluster Evaluation',
          'format' => NULL,
          'safe_value' => 'Cluster Evaluation',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Cluster Evaluation',
          'format' => NULL,
          'safe_value' => 'Cluster Evaluation',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'An evaluative review of the work done by the cluster and the coordination teams',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>An evaluative review of the work done by the cluster and the coordination teams</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'An evaluative review of the work done by the cluster and the coordination teams',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>An evaluative review of the work done by the cluster and the coordination teams</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Cluster Evaluation',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 23,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562342,
          'changed' => 1422562342,
        ),
      ),
    ),
    'description_original' => 'An evaluative review of the work done by the cluster and the coordination teams',
  );
  $terms[] = array(
    'name' => 'Community Participation',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '014cd41f-a671-4ac6-8bdb-22418c7630bd',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Community Participation',
          'format' => NULL,
          'safe_value' => 'Community Participation',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Community Participation',
          'format' => NULL,
          'safe_value' => 'Community Participation',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Community Participation',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 24,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Technical Training',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '01932662-8e57-4420-8a0f-3c021ceeac9e',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Technical Training',
          'format' => NULL,
          'safe_value' => 'Technical Training',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Technical Training',
          'format' => NULL,
          'safe_value' => 'Technical Training',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Technical Training',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 25,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Risk Reduction',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0266edff-6a91-4e3d-a42a-96df3605c9ad',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Risk Reduction',
          'format' => NULL,
          'safe_value' => 'Risk Reduction',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Risk Reduction',
          'format' => NULL,
          'safe_value' => 'Risk Reduction',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Risk Reduction',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 26,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Human Rights',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => '05777ad3-81a1-47e6-ae27-cd1a23bd7c1b',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Human Rights',
          'format' => NULL,
          'safe_value' => 'Human Rights',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Human Rights',
          'format' => NULL,
          'safe_value' => 'Human Rights',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Human Rights',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 27,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Livestock',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '077fb354-c0d9-494f-8248-7a934e3e085c',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Livestock',
          'format' => NULL,
          'safe_value' => 'Livestock',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Livestock',
          'format' => NULL,
          'safe_value' => 'Livestock',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Livestock',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 28,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Template',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '082341aa-3100-4d3e-8963-2dfb268aba81',
    'vocabulary_machine_name' => 'toolkit',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Template',
          'format' => NULL,
          'safe_value' => 'Template',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Template',
          'format' => NULL,
          'safe_value' => 'Template',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Template',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562742,
          'changed' => 1422562742,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Tools and Fixing',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0d579851-10c8-49bc-91ec-700b2bba1dea',
    'vocabulary_machine_name' => 'non_food_items',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Tools and Fixing',
          'format' => NULL,
          'safe_value' => 'Tools and Fixing',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Tools and Fixing',
          'format' => NULL,
          'safe_value' => 'Tools and Fixing',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Tools and Fixing',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 29,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562691,
          'changed' => 1422562691,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Inter-Cluster',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '1d5f2d64-dfb7-4695-a693-db8c232ade2b',
    'vocabulary_machine_name' => 'document_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Inter-Cluster',
          'format' => NULL,
          'safe_value' => 'Inter-Cluster',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Inter-Cluster',
          'format' => NULL,
          'safe_value' => 'Inter-Cluster',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Inter-Cluster',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 138,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562671,
          'changed' => 1422562671,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Government and regulatory policy',
    'description' => 'Documentation on government policies, legislation, building codes, etc.',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '20bbc6c4-2b8f-4fb2-a008-d88545054ab3',
    'vocabulary_machine_name' => 'coordination_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Government and regulatory policy',
          'format' => NULL,
          'safe_value' => 'Government and regulatory policy',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Government and regulatory policy',
          'format' => NULL,
          'safe_value' => 'Government and regulatory policy',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Documentation on government policies, legislation, building codes, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation on government policies, legislation, building codes, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Documentation on government policies, legislation, building codes, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation on government policies, legislation, building codes, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Government and regulatory policy',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 31,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562255,
          'changed' => 1422562255,
        ),
      ),
    ),
    'description_original' => 'Documentation on government policies, legislation, building codes, etc.',
  );
  $terms[] = array(
    'name' => 'HIV/AIDS',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => '2105392a-1960-4c54-b53d-67e4b7761570',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'HIV/AIDS',
          'format' => NULL,
          'safe_value' => 'HIV/AIDS',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'HIV/AIDS',
          'format' => NULL,
          'safe_value' => 'HIV/AIDS',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'HIV/AIDS',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 32,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'No-build Zones',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2256cb0a-0126-4593-b760-318960e1833d',
    'vocabulary_machine_name' => 'issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'No-build Zones',
          'format' => NULL,
          'safe_value' => 'No-build Zones',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'No-build Zones',
          'format' => NULL,
          'safe_value' => 'No-build Zones',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'No-build Zones',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 33,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562725,
          'changed' => 1422562725,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Assessment, Monitoring, and Evaluation',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '23f38dd8-ce9d-4a11-b750-1ee3498b0568',
    'vocabulary_machine_name' => 'information_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Assessment, Monitoring, and Evaluation',
          'format' => NULL,
          'safe_value' => 'Assessment, Monitoring, and Evaluation',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Assessment, Monitoring, and Evaluation',
          'format' => NULL,
          'safe_value' => 'Assessment, Monitoring, and Evaluation',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Assessment, Monitoring, and Evaluation',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 137,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562549,
          'changed' => 1422562549,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Cash and Vouchers',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2a3d473e-5365-4bfc-afd1-6d5e8cded390',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Cash and Vouchers',
          'format' => NULL,
          'safe_value' => 'Cash and Vouchers',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Cash and Vouchers',
          'format' => NULL,
          'safe_value' => 'Cash and Vouchers',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Cash and Vouchers',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 35,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Age',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => '2b7910a2-a7e7-475a-b0ea-9a4f3ef3e0ea',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Age',
          'format' => NULL,
          'safe_value' => 'Age',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Age',
          'format' => NULL,
          'safe_value' => 'Age',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Age',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 36,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Checklist',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2bd09893-bad4-4a87-8e33-280bcee5caf7',
    'vocabulary_machine_name' => 'toolkit',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Checklist',
          'format' => NULL,
          'safe_value' => 'Checklist',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Checklist',
          'format' => NULL,
          'safe_value' => 'Checklist',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Checklist',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 139,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562742,
          'changed' => 1422562742,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Winterization',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2c670010-8b2b-4c10-b5c1-da4931b7151d',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Winterization',
          'format' => NULL,
          'safe_value' => 'Winterization',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Winterization',
          'format' => NULL,
          'safe_value' => 'Winterization',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Winterization',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 37,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Early Recovery',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '3011fe7c-a1fd-4e09-8c0a-a012a23d58c2',
    'vocabulary_machine_name' => 'inter_cluster',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Early Recovery',
          'format' => NULL,
          'safe_value' => 'Early Recovery',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Early Recovery',
          'format' => NULL,
          'safe_value' => 'Early Recovery',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Early Recovery',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 38,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562566,
          'changed' => 1422562566,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Masonry',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3132d7be-184f-4741-902d-26dac71134c0',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Masonry',
          'format' => NULL,
          'safe_value' => 'Masonry',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Masonry',
          'format' => NULL,
          'safe_value' => 'Masonry',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Masonry',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 40,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Example',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '32c7e9ea-196e-4c9a-8157-982d5970c906',
    'vocabulary_machine_name' => 'toolkit',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Example',
          'format' => NULL,
          'safe_value' => 'Example',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Example',
          'format' => NULL,
          'safe_value' => 'Example',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Example',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 41,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562742,
          'changed' => 1422562742,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Host Families',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3340ec31-8e35-4913-8e17-6eb67fd22726',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Host Families',
          'format' => NULL,
          'safe_value' => 'Host Families',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Host Families',
          'format' => NULL,
          'safe_value' => 'Host Families',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Host Families',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 42,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Disabilities',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '33a0a3be-6c3b-4afc-9aa0-719eb1888c47',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Disabilities',
          'format' => NULL,
          'safe_value' => 'Disabilities',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Disabilities',
          'format' => NULL,
          'safe_value' => 'Disabilities',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Disabilities',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 43,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Environment',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '341f24cf-d447-4890-8884-22e01cf0d126',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Environment',
          'format' => NULL,
          'safe_value' => 'Environment',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Environment',
          'format' => NULL,
          'safe_value' => 'Environment',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Environment',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 44,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Non Food Items',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '38efa47c-c6ef-4e0c-9747-8858eee7791f',
    'vocabulary_machine_name' => 'document_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Non Food Items',
          'format' => NULL,
          'safe_value' => 'Non Food Items',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Non Food Items',
          'format' => NULL,
          'safe_value' => 'Non Food Items',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Non Food Items',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 140,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562671,
          'changed' => 1422562671,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Owner-occupier',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3a7ddfd1-3263-4f2c-963a-a3f2d3add412',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Owner-occupier',
          'format' => NULL,
          'safe_value' => 'Owner-occupier',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Owner-occupier',
          'format' => NULL,
          'safe_value' => 'Owner-occupier',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Owner-occupier',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 45,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Agency Assessment',
    'description' => 'A report from an independent assessment conducted by an agency in the cluster',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3b1e3d1a-3753-481e-93c5-443f897cd4dc',
    'vocabulary_machine_name' => 'assessment_monitoring_evaluation',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Agency Assessment',
          'format' => NULL,
          'safe_value' => 'Agency Assessment',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Agency Assessment',
          'format' => NULL,
          'safe_value' => 'Agency Assessment',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'A report from an independent assessment conducted by an agency in the cluster',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>A report from an independent assessment conducted by an agency in the cluster</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'A report from an independent assessment conducted by an agency in the cluster',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>A report from an independent assessment conducted by an agency in the cluster</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Agency Assessment',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 46,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562342,
          'changed' => 1422562342,
        ),
      ),
    ),
    'description_original' => 'A report from an independent assessment conducted by an agency in the cluster',
  );
  $terms[] = array(
    'name' => 'Shelter Programming',
    'description' => 'Guidance related to the modalities of shelter interventions such as cash, support to host famililies, distributions, etc.',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '3c0c5890-95b3-472b-9edb-ec224fc154f5',
    'vocabulary_machine_name' => 'technical_support_design',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Shelter Programming',
          'format' => NULL,
          'safe_value' => 'Shelter Programming',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Shelter Programming',
          'format' => NULL,
          'safe_value' => 'Shelter Programming',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Guidance related to the modalities of shelter interventions such as cash, support to host famililies, distributions, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Guidance related to the modalities of shelter interventions such as cash, support to host famililies, distributions, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Guidance related to the modalities of shelter interventions such as cash, support to host famililies, distributions, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Guidance related to the modalities of shelter interventions such as cash, support to host famililies, distributions, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Shelter Programming',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 47,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562531,
          'changed' => 1422562531,
        ),
      ),
    ),
    'description_original' => 'Guidance related to the modalities of shelter interventions such as cash, support to host famililies, distributions, etc.',
  );
  $terms[] = array(
    'name' => 'Secondary Data Review',
    'description' => 'An assessment report resulting from the analysis of available secondary data',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '3d20e159-f152-4fad-8f22-a8fa70a29b4b',
    'vocabulary_machine_name' => 'assessment_monitoring_evaluation',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Secondary Data Review',
          'format' => NULL,
          'safe_value' => 'Secondary Data Review',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Secondary Data Review',
          'format' => NULL,
          'safe_value' => 'Secondary Data Review',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'An assessment report resulting from the analysis of available secondary data',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>An assessment report resulting from the analysis of available secondary data</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'An assessment report resulting from the analysis of available secondary data',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>An assessment report resulting from the analysis of available secondary data</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Secondary Data Review',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 5,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562342,
          'changed' => 1422562342,
        ),
      ),
    ),
    'description_original' => 'An assessment report resulting from the analysis of available secondary data',
  );
  $terms[] = array(
    'name' => 'Technical Guidance',
    'description' => 'Documentation of suggested technical standards and program modalities',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3d32ad02-1b19-443e-a6bb-28484d1febca',
    'vocabulary_machine_name' => 'technical_support_design',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Technical Guidance',
          'format' => NULL,
          'safe_value' => 'Technical Guidance',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Technical Guidance',
          'format' => NULL,
          'safe_value' => 'Technical Guidance',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Documentation of suggested technical standards and program modalities',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation of suggested technical standards and program modalities</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Documentation of suggested technical standards and program modalities',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation of suggested technical standards and program modalities</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Technical Guidance',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 6,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562531,
          'changed' => 1422562531,
        ),
      ),
    ),
    'description_original' => 'Documentation of suggested technical standards and program modalities',
  );
  $terms[] = array(
    'name' => 'Repairs and Retrofitting',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3f022da5-4867-44da-ad50-2a4343457524',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Repairs and Retrofitting',
          'format' => NULL,
          'safe_value' => 'Repairs and Retrofitting',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Repairs and Retrofitting',
          'format' => NULL,
          'safe_value' => 'Repairs and Retrofitting',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Repairs and Retrofitting',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 48,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Core Shelters',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3f1e57ba-3da5-4530-9acc-8b6e21ce579d',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Core Shelters',
          'format' => NULL,
          'safe_value' => 'Core Shelters',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Core Shelters',
          'format' => NULL,
          'safe_value' => 'Core Shelters',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Core Shelters',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 49,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Distribution',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3ffc180f-cc18-4dbf-bdc1-9bd70da2be8b',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Distribution',
          'format' => NULL,
          'safe_value' => 'Distribution',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Distribution',
          'format' => NULL,
          'safe_value' => 'Distribution',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Distribution',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 50,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Beneficiary Communications',
    'description' => 'Documents related to messaging that is specifically targetted towards affected populations',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '469926b7-f52d-4fc1-8484-cca05acff9ac',
    'vocabulary_machine_name' => 'information_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Beneficiary Communications',
          'format' => NULL,
          'safe_value' => 'Beneficiary Communications',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Beneficiary Communications',
          'format' => NULL,
          'safe_value' => 'Beneficiary Communications',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Documents related to messaging that is specifically targetted towards affected populations',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documents related to messaging that is specifically targetted towards affected populations</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Documents related to messaging that is specifically targetted towards affected populations',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documents related to messaging that is specifically targetted towards affected populations</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Beneficiary Communications',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 51,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562549,
          'changed' => 1422562549,
        ),
      ),
    ),
    'description_original' => 'Documents related to messaging that is specifically targetted towards affected populations',
  );
  $terms[] = array(
    'name' => 'WASH',
    'description' => 'Water, Sanitation, and Hygiene Promotion',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '48e39189-ed6d-4527-94ff-219a99460b50',
    'vocabulary_machine_name' => 'inter_cluster',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'WASH',
          'format' => NULL,
          'safe_value' => 'WASH',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'WASH',
          'format' => NULL,
          'safe_value' => 'WASH',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Water, Sanitation, and Hygiene Promotion',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Water, Sanitation, and Hygiene Promotion</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Water, Sanitation, and Hygiene Promotion',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Water, Sanitation, and Hygiene Promotion</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'WASH',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 52,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562566,
          'changed' => 1422562566,
        ),
      ),
    ),
    'description_original' => 'Water, Sanitation, and Hygiene Promotion',
  );
  $terms[] = array(
    'name' => 'Procurement and Logistics',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4a4a3f8e-95a0-466d-93c7-fbb8f70d314f',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Procurement and Logistics',
          'format' => NULL,
          'safe_value' => 'Procurement and Logistics',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Procurement and Logistics',
          'format' => NULL,
          'safe_value' => 'Procurement and Logistics',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Procurement and Logistics',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 53,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Meeting Management',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '51cbff1f-021a-43a1-8429-e66c958b98e1',
    'vocabulary_machine_name' => 'coordination_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Meeting Management',
          'format' => NULL,
          'safe_value' => 'Meeting Management',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Meeting Management',
          'format' => NULL,
          'safe_value' => 'Meeting Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Meeting Management',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 7,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562255,
          'changed' => 1422562255,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Displacement Tracking',
    'description' => 'Reporting on the movement and settlement conditions of displaced populations',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '55eaac52-8a6e-4b6f-a638-ad017ac423a5',
    'vocabulary_machine_name' => 'assessment_monitoring_evaluation',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Displacement Tracking',
          'format' => NULL,
          'safe_value' => 'Displacement Tracking',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Displacement Tracking',
          'format' => NULL,
          'safe_value' => 'Displacement Tracking',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Reporting on the movement and settlement conditions of displaced populations',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Reporting on the movement and settlement conditions of displaced populations</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Reporting on the movement and settlement conditions of displaced populations',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Reporting on the movement and settlement conditions of displaced populations</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Displacement Tracking',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 55,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562342,
          'changed' => 1422562342,
        ),
      ),
    ),
    'description_original' => 'Reporting on the movement and settlement conditions of displaced populations',
  );
  $terms[] = array(
    'name' => 'Informal Settlements',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5667a7a0-2f99-4d3c-8c50-0a6787018fac',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Informal Settlements',
          'format' => NULL,
          'safe_value' => 'Informal Settlements',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Informal Settlements',
          'format' => NULL,
          'safe_value' => 'Informal Settlements',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Informal Settlements',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 56,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Organic Enclosures',
    'description' => 'woven grass, etc.',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '566e2413-d81d-433e-8ea4-b1ca731429e8',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Organic Enclosures',
          'format' => NULL,
          'safe_value' => 'Organic Enclosures',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Organic Enclosures',
          'format' => NULL,
          'safe_value' => 'Organic Enclosures',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'woven grass, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>woven grass, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'woven grass, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>woven grass, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Organic Enclosures',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 57,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => 'woven grass, etc.',
  );
  $terms[] = array(
    'name' => 'Relocations',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '58bf77fd-355f-45c9-a44e-db012198fb85',
    'vocabulary_machine_name' => 'issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Relocations',
          'format' => NULL,
          'safe_value' => 'Relocations',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Relocations',
          'format' => NULL,
          'safe_value' => 'Relocations',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Relocations',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 9,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562725,
          'changed' => 1422562725,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Market Assessment',
    'description' => 'A report from an assessment that examines the economic or market functions for a particular area',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '5c1974d1-9a4e-4087-b378-98fa9fa41cea',
    'vocabulary_machine_name' => 'assessment_monitoring_evaluation',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Market Assessment',
          'format' => NULL,
          'safe_value' => 'Market Assessment',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Market Assessment',
          'format' => NULL,
          'safe_value' => 'Market Assessment',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'A report from an assessment that examines the economic or market functions for a particular area',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>A report from an assessment that examines the economic or market functions for a particular area</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'A report from an assessment that examines the economic or market functions for a particular area',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>A report from an assessment that examines the economic or market functions for a particular area</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Market Assessment',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 58,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562342,
          'changed' => 1422562342,
        ),
      ),
    ),
    'description_original' => 'A report from an assessment that examines the economic or market functions for a particular area',
  );
  $terms[] = array(
    'name' => 'Aggregates',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5ca47229-9652-42df-a41d-63520fec5349',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Aggregates',
          'format' => NULL,
          'safe_value' => 'Aggregates',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Aggregates',
          'format' => NULL,
          'safe_value' => 'Aggregates',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Aggregates',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 10,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Reconstruction',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '5f7d4a03-5d53-477e-bea1-178ed4ae5d0e',
    'vocabulary_machine_name' => 'response_phase',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Reconstruction',
          'format' => NULL,
          'safe_value' => 'Reconstruction',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Reconstruction',
          'format' => NULL,
          'safe_value' => 'Reconstruction',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Reconstruction',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 60,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562601,
          'changed' => 1422562601,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Toolkit',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '655dbcc6-04d8-447f-9c8e-2aed8e14f12a',
    'vocabulary_machine_name' => 'document_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Toolkit',
          'format' => NULL,
          'safe_value' => 'Toolkit',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Toolkit',
          'format' => NULL,
          'safe_value' => 'Toolkit',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Toolkit',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 141,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562671,
          'changed' => 1422562671,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Multi-tenant Apartment',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6a6fefac-f15b-4bf5-8223-e968c8cdcd6f',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Multi-tenant Apartment',
          'format' => NULL,
          'safe_value' => 'Multi-tenant Apartment',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Multi-tenant Apartment',
          'format' => NULL,
          'safe_value' => 'Multi-tenant Apartment',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Multi-tenant Apartment',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 62,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Cooking and Eating Utensils',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6a7e7965-a162-4844-beae-3b5a6d955608',
    'vocabulary_machine_name' => 'non_food_items',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Cooking and Eating Utensils',
          'format' => NULL,
          'safe_value' => 'Cooking and Eating Utensils',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Cooking and Eating Utensils',
          'format' => NULL,
          'safe_value' => 'Cooking and Eating Utensils',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Cooking and Eating Utensils',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 63,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562691,
          'changed' => 1422562691,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Health',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '6aef3fa1-7c39-446e-a757-dcbd3e5ab137',
    'vocabulary_machine_name' => 'inter_cluster',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Health',
          'format' => NULL,
          'safe_value' => 'Health',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Health',
          'format' => NULL,
          'safe_value' => 'Health',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Health',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 64,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562566,
          'changed' => 1422562566,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Mines and other explosives',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6b730f77-36ba-4937-959d-45031f626cc4',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Mines and other explosives',
          'format' => NULL,
          'safe_value' => 'Mines and other explosives',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Mines and other explosives',
          'format' => NULL,
          'safe_value' => 'Mines and other explosives',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Mines and other explosives',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 65,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Returns to Area of Origin',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '70472c91-e109-482d-a0f1-f91de81ad9d0',
    'vocabulary_machine_name' => 'issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Returns to Area of Origin',
          'format' => NULL,
          'safe_value' => 'Returns to Area of Origin',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Returns to Area of Origin',
          'format' => NULL,
          'safe_value' => 'Returns to Area of Origin',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Returns to Area of Origin',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 66,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562725,
          'changed' => 1422562725,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Situation Report',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '766c6fbe-c3ea-41c0-9180-1b3c5129c218',
    'vocabulary_machine_name' => 'coordination_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Situation Report',
          'format' => NULL,
          'safe_value' => 'Situation Report',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Situation Report',
          'format' => NULL,
          'safe_value' => 'Situation Report',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Situation Report',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 142,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562255,
          'changed' => 1422562255,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Maps and GIS',
    'description' => 'Graphic mapping products',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '79772c36-ed3f-4cbf-99f1-c3361a854563',
    'vocabulary_machine_name' => 'information_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Maps and GIS',
          'format' => NULL,
          'safe_value' => 'Maps and GIS',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Maps and GIS',
          'format' => NULL,
          'safe_value' => 'Maps and GIS',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Graphic mapping products',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Graphic mapping products</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Graphic mapping products',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Graphic mapping products</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Maps and GIS',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 11,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562549,
          'changed' => 1422562549,
        ),
      ),
    ),
    'description_original' => 'Graphic mapping products',
  );
  $terms[] = array(
    'name' => 'Logistics',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => '7b5eff48-bd93-470c-b68d-166700a94dc6',
    'vocabulary_machine_name' => 'inter_cluster',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Logistics',
          'format' => NULL,
          'safe_value' => 'Logistics',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Logistics',
          'format' => NULL,
          'safe_value' => 'Logistics',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Logistics',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 67,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562566,
          'changed' => 1422562566,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Communications Messaging',
    'description' => 'Documentation that illustrate key messaging of advocacy messages targeted to stakeholders of the cluster and media',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '7eafa2d9-220d-44bc-a0ff-fe5b759065fe',
    'vocabulary_machine_name' => 'information_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Communications Messaging',
          'format' => NULL,
          'safe_value' => 'Communications Messaging',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Communications Messaging',
          'format' => NULL,
          'safe_value' => 'Communications Messaging',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Documentation that illustrate key messaging of advocacy messages targeted to stakeholders of the cluster and media',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation that illustrate key messaging of advocacy messages targeted to stakeholders of the cluster and media</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Documentation that illustrate key messaging of advocacy messages targeted to stakeholders of the cluster and media',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation that illustrate key messaging of advocacy messages targeted to stakeholders of the cluster and media</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Communications Messaging',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 68,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562549,
          'changed' => 1422562549,
        ),
      ),
    ),
    'description_original' => 'Documentation that illustrate key messaging of advocacy messages targeted to stakeholders of the cluster and media',
  );
  $terms[] = array(
    'name' => 'Rentals and tenants',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '848d416c-f6d8-499e-b4ae-6009972d7472',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Rentals and tenants',
          'format' => NULL,
          'safe_value' => 'Rentals and tenants',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Rentals and tenants',
          'format' => NULL,
          'safe_value' => 'Rentals and tenants',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Rentals and tenants',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 69,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Rubble Removal',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '88aa7163-7706-4995-8a90-a7f3ff0eb1c4',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Rubble Removal',
          'format' => NULL,
          'safe_value' => 'Rubble Removal',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Rubble Removal',
          'format' => NULL,
          'safe_value' => 'Rubble Removal',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Rubble Removal',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 70,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Urban Planning',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8d113a79-37ad-4c1e-8a9e-4d1dbcc7a9db',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Urban Planning',
          'format' => NULL,
          'safe_value' => 'Urban Planning',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Urban Planning',
          'format' => NULL,
          'safe_value' => 'Urban Planning',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Urban Planning',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 71,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Guidance',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '91919635-562a-4735-ad43-7957fad923b7',
    'vocabulary_machine_name' => 'toolkit',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Guidance',
          'format' => NULL,
          'safe_value' => 'Guidance',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Guidance',
          'format' => NULL,
          'safe_value' => 'Guidance',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Guidance',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 72,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562742,
          'changed' => 1422562742,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Protection',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '92a901cb-5e56-4bbb-956c-68bbcb72190b',
    'vocabulary_machine_name' => 'inter_cluster',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Protection',
          'format' => NULL,
          'safe_value' => 'Protection',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Protection',
          'format' => NULL,
          'safe_value' => 'Protection',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Protection',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 73,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562566,
          'changed' => 1422562566,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Stoves, Fuel, and Lighting',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '94029900-c28c-4ec7-ab42-f44b83ec71c0',
    'vocabulary_machine_name' => 'non_food_items',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Stoves, Fuel, and Lighting',
          'format' => NULL,
          'safe_value' => 'Stoves, Fuel, and Lighting',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Stoves, Fuel, and Lighting',
          'format' => NULL,
          'safe_value' => 'Stoves, Fuel, and Lighting',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Stoves, Fuel, and Lighting',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 74,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562691,
          'changed' => 1422562691,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Resource Mobilization',
    'description' => 'Appeals, Strategic response plan, CERF, CAP documents',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '97f29998-777b-4b0f-a7fb-41998310e5c2',
    'vocabulary_machine_name' => 'coordination_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Resource Mobilization',
          'format' => NULL,
          'safe_value' => 'Resource Mobilization',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Resource Mobilization',
          'format' => NULL,
          'safe_value' => 'Resource Mobilization',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Appeals, Strategic response plan, CERF, CAP documents',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Appeals, Strategic response plan, CERF, CAP documents</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Appeals, Strategic response plan, CERF, CAP documents',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Appeals, Strategic response plan, CERF, CAP documents</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Resource Mobilization',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 75,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562255,
          'changed' => 1422562255,
        ),
      ),
    ),
    'description_original' => 'Appeals, Strategic response plan, CERF, CAP documents',
  );
  $terms[] = array(
    'name' => 'Design Specifications',
    'description' => 'Detailed information on construction design, bills of quantity, costing, etc.',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '9b0e5aa2-2232-4dc7-bd39-f466c336082c',
    'vocabulary_machine_name' => 'technical_support_design',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Design Specifications',
          'format' => NULL,
          'safe_value' => 'Design Specifications',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Design Specifications',
          'format' => NULL,
          'safe_value' => 'Design Specifications',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Detailed information on construction design, bills of quantity, costing, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Detailed information on construction design, bills of quantity, costing, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Detailed information on construction design, bills of quantity, costing, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Detailed information on construction design, bills of quantity, costing, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Design Specifications',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 76,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562531,
          'changed' => 1422562531,
        ),
      ),
    ),
    'description_original' => 'Detailed information on construction design, bills of quantity, costing, etc.',
  );
  $terms[] = array(
    'name' => 'Children',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '9fd846ed-7e25-4edd-bc9f-e9901b828ecb',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Children',
          'format' => NULL,
          'safe_value' => 'Children',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Children',
          'format' => NULL,
          'safe_value' => 'Children',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Children',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 78,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Housing, Land, and Property Rights',
    'description' => 'Housing, Land, and Property Rights',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => 'a023e414-c655-431a-bd7c-70cf25ab084c',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Housing, Land, and Property Rights',
          'format' => NULL,
          'safe_value' => 'Housing, Land, and Property Rights',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Housing, Land, and Property Rights',
          'format' => NULL,
          'safe_value' => 'Housing, Land, and Property Rights',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Housing, Land, and Property Rights',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Housing, Land, and Property Rights</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Housing, Land, and Property Rights',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Housing, Land, and Property Rights</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Housing, Land, and Property Rights',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 79,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => 'Housing, Land, and Property Rights',
  );
  $terms[] = array(
    'name' => 'Emergency Shelter',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a20c44ff-3ef9-4b14-852a-cb3b09d86232',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Emergency Shelter',
          'format' => NULL,
          'safe_value' => 'Emergency Shelter',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Emergency Shelter',
          'format' => NULL,
          'safe_value' => 'Emergency Shelter',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Emergency Shelter',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 80,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Tools and Shelter Kits',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a2b3aed6-4802-46df-ac17-ff4cad4705cd',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Tools and Shelter Kits',
          'format' => NULL,
          'safe_value' => 'Tools and Shelter Kits',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Tools and Shelter Kits',
          'format' => NULL,
          'safe_value' => 'Tools and Shelter Kits',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Tools and Shelter Kits',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 83,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Timber',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a44fc26c-9a15-49d2-80f5-ecd544ea5b81',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Timber',
          'format' => NULL,
          'safe_value' => 'Timber',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Timber',
          'format' => NULL,
          'safe_value' => 'Timber',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Timber',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 84,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'CCCM',
    'description' => 'Camp Coordination and Camp Management',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'a54e745a-d963-4e42-83e2-f12af8aa057b',
    'vocabulary_machine_name' => 'inter_cluster',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'CCCM',
          'format' => NULL,
          'safe_value' => 'CCCM',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'CCCM',
          'format' => NULL,
          'safe_value' => 'CCCM',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Camp Coordination and Camp Management',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Camp Coordination and Camp Management</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Camp Coordination and Camp Management',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Camp Coordination and Camp Management</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'CCCM',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 85,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562566,
          'changed' => 1422562566,
        ),
      ),
    ),
    'description_original' => 'Camp Coordination and Camp Management',
  );
  $terms[] = array(
    'name' => 'Non-displaced',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a6a05846-68e2-4663-ba56-cc7d8016116c',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Non-displaced',
          'format' => NULL,
          'safe_value' => 'Non-displaced',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Non-displaced',
          'format' => NULL,
          'safe_value' => 'Non-displaced',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Non-displaced',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 86,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Host Family Support',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a756083b-3669-4f15-acca-853cedac05a0',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Host Family Support',
          'format' => NULL,
          'safe_value' => 'Host Family Support',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Host Family Support',
          'format' => NULL,
          'safe_value' => 'Host Family Support',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Host Family Support',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 87,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Formal Camps',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a80f90df-0c7f-4e10-a22f-c1b901666f3e',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Formal Camps',
          'format' => NULL,
          'safe_value' => 'Formal Camps',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Formal Camps',
          'format' => NULL,
          'safe_value' => 'Formal Camps',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Formal Camps',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 12,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Built Environment Professionals',
    'description' => 'engagement of engineers, architects, planners, etc',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a8c3fd93-28e4-4fb9-9aaa-734e271a0572',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Built Environment Professionals',
          'format' => NULL,
          'safe_value' => 'Built Environment Professionals',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Built Environment Professionals',
          'format' => NULL,
          'safe_value' => 'Built Environment Professionals',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'engagement of engineers, architects, planners, etc',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>engagement of engineers, architects, planners, etc</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'engagement of engineers, architects, planners, etc',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>engagement of engineers, architects, planners, etc</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Built Environment Professionals',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 88,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => 'engagement of engineers, architects, planners, etc',
  );
  $terms[] = array(
    'name' => 'Permanent Housing',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'aa31af83-42c8-40e5-81be-079bd2249160',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Permanent Housing',
          'format' => NULL,
          'safe_value' => 'Permanent Housing',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Permanent Housing',
          'format' => NULL,
          'safe_value' => 'Permanent Housing',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Permanent Housing',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 89,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Emergency',
    'description' => 'Typically associated with life-saving activities',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'ae4af7fb-0364-43a7-8ae1-98708ab92610',
    'vocabulary_machine_name' => 'response_phase',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Emergency',
          'format' => NULL,
          'safe_value' => 'Emergency',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Emergency',
          'format' => NULL,
          'safe_value' => 'Emergency',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Typically associated with life-saving activities',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Typically associated with life-saving activities</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Typically associated with life-saving activities',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Typically associated with life-saving activities</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Emergency',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 90,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562601,
          'changed' => 1422562601,
        ),
      ),
    ),
    'description_original' => 'Typically associated with life-saving activities',
  );
  $terms[] = array(
    'name' => 'Demolition',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'af363042-bcae-49e9-878b-b040b983533b',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Demolition',
          'format' => NULL,
          'safe_value' => 'Demolition',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Demolition',
          'format' => NULL,
          'safe_value' => 'Demolition',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Demolition',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 91,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Multi-sectoral Assessment',
    'description' => 'A report for an assessment that involves several cluster such as a MIRA',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'af7249ca-f0eb-4a64-82ba-c25322e32d61',
    'vocabulary_machine_name' => 'assessment_monitoring_evaluation',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Multi-sectoral Assessment',
          'format' => NULL,
          'safe_value' => 'Multi-sectoral Assessment',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Multi-sectoral Assessment',
          'format' => NULL,
          'safe_value' => 'Multi-sectoral Assessment',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'A report for an assessment that involves several cluster such as a MIRA',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>A report for an assessment that involves several cluster such as a MIRA</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'A report for an assessment that involves several cluster such as a MIRA',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>A report for an assessment that involves several cluster such as a MIRA</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Multi-sectoral Assessment',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 92,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562342,
          'changed' => 1422562342,
        ),
      ),
    ),
    'description_original' => 'A report for an assessment that involves several cluster such as a MIRA',
  );
  $terms[] = array(
    'name' => 'General Household Support',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b1599173-047e-45e4-ab3a-cb8fe0b86516',
    'vocabulary_machine_name' => 'non_food_items',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'General Household Support',
          'format' => NULL,
          'safe_value' => 'General Household Support',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'General Household Support',
          'format' => NULL,
          'safe_value' => 'General Household Support',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'General Household Support',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 95,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562691,
          'changed' => 1422562691,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Bamboo',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b47e81be-d6b1-4db7-9f0a-c48186cfbd72',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Bamboo',
          'format' => NULL,
          'safe_value' => 'Bamboo',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Bamboo',
          'format' => NULL,
          'safe_value' => 'Bamboo',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Bamboo',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 98,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Bunkhouses',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b50b507f-a52d-4360-9f6a-5325b4123a9f',
    'vocabulary_machine_name' => 'issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Bunkhouses',
          'format' => NULL,
          'safe_value' => 'Bunkhouses',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Bunkhouses',
          'format' => NULL,
          'safe_value' => 'Bunkhouses',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Bunkhouses',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 99,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562725,
          'changed' => 1422562725,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Metal Sheeting',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b75b8716-c089-485c-8c0b-4d932d17920c',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Metal Sheeting',
          'format' => NULL,
          'safe_value' => 'Metal Sheeting',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Metal Sheeting',
          'format' => NULL,
          'safe_value' => 'Metal Sheeting',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Metal Sheeting',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 100,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Steel',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b975b04a-54f4-4ade-a093-b359bf042909',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Steel',
          'format' => NULL,
          'safe_value' => 'Steel',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Steel',
          'format' => NULL,
          'safe_value' => 'Steel',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Steel',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 101,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Concrete',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b99e7560-a88b-4290-9622-9b18fedb977b',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Concrete',
          'format' => NULL,
          'safe_value' => 'Concrete',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Concrete',
          'format' => NULL,
          'safe_value' => 'Concrete',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Concrete',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 102,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Plastic Sheeting',
    'description' => 'Tarpaulines, rolls, sheets',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'be7b432b-84f8-4369-a657-972cfec22e0c',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Plastic Sheeting',
          'format' => NULL,
          'safe_value' => 'Plastic Sheeting',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Plastic Sheeting',
          'format' => NULL,
          'safe_value' => 'Plastic Sheeting',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Tarpaulines, rolls, sheets',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Tarpaulines, rolls, sheets</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Tarpaulines, rolls, sheets',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Tarpaulines, rolls, sheets</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Plastic Sheeting',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 103,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => 'Tarpaulines, rolls, sheets',
  );
  $terms[] = array(
    'name' => 'Advisory Note',
    'description' => 'Documents to clarify cluster positions on various thematic topics',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'beca793a-cad5-4348-aba4-856d5010f133',
    'vocabulary_machine_name' => 'coordination_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Advisory Note',
          'format' => NULL,
          'safe_value' => 'Advisory Note',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Advisory Note',
          'format' => NULL,
          'safe_value' => 'Advisory Note',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Documents to clarify cluster positions on various thematic topics',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documents to clarify cluster positions on various thematic topics</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Documents to clarify cluster positions on various thematic topics',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documents to clarify cluster positions on various thematic topics</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Advisory Note',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 104,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562255,
          'changed' => 1422562255,
        ),
      ),
    ),
    'description_original' => 'Documents to clarify cluster positions on various thematic topics',
  );
  $terms[] = array(
    'name' => 'Reporting Tools and Guidance',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c310630e-6f3b-4b42-b289-84b398f3cdf0',
    'vocabulary_machine_name' => 'information_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Reporting Tools and Guidance',
          'format' => NULL,
          'safe_value' => 'Reporting Tools and Guidance',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Reporting Tools and Guidance',
          'format' => NULL,
          'safe_value' => 'Reporting Tools and Guidance',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Reporting Tools and Guidance',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 143,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562549,
          'changed' => 1422562549,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Coordination Management',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c7a0e1d1-5103-4b5b-aae2-27d9d05565c5',
    'vocabulary_machine_name' => 'document_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Coordination Management',
          'format' => NULL,
          'safe_value' => 'Coordination Management',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Coordination Management',
          'format' => NULL,
          'safe_value' => 'Coordination Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Coordination Management',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 144,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562671,
          'changed' => 1422562671,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Information Management',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'c7f9469a-d1c7-408a-abab-06370828cc10',
    'vocabulary_machine_name' => 'document_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Information Management',
          'format' => NULL,
          'safe_value' => 'Information Management',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Information Management',
          'format' => NULL,
          'safe_value' => 'Information Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Information Management',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 145,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562671,
          'changed' => 1422562671,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Infographic',
    'description' => 'Visual image representing information used to communicate a set of messages related to the crisis',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'c8f1e2b4-dd4f-4b39-854d-cb2c11a6ad96',
    'vocabulary_machine_name' => 'information_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Infographic',
          'format' => NULL,
          'safe_value' => 'Infographic',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Infographic',
          'format' => NULL,
          'safe_value' => 'Infographic',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Visual image representing information used to communicate a set of messages related to the crisis',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Visual image representing information used to communicate a set of messages related to the crisis</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Visual image representing information used to communicate a set of messages related to the crisis',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Visual image representing information used to communicate a set of messages related to the crisis</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Infographic',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 105,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562549,
          'changed' => 1422562549,
        ),
      ),
    ),
    'description_original' => 'Visual image representing information used to communicate a set of messages related to the crisis',
  );
  $terms[] = array(
    'name' => 'Early Recovery',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'c94e35b1-95ea-4bc9-b109-c18a5727585c',
    'vocabulary_machine_name' => 'response_phase',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Early Recovery',
          'format' => NULL,
          'safe_value' => 'Early Recovery',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Early Recovery',
          'format' => NULL,
          'safe_value' => 'Early Recovery',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Early Recovery',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 107,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562601,
          'changed' => 1422562601,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Technical Support and Design',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'ca658eeb-8879-4d7a-a63a-26836c654086',
    'vocabulary_machine_name' => 'document_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Technical Support and Design',
          'format' => NULL,
          'safe_value' => 'Technical Support and Design',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Technical Support and Design',
          'format' => NULL,
          'safe_value' => 'Technical Support and Design',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Technical Support and Design',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 146,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562671,
          'changed' => 1422562671,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Construction Methods',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ca785653-f9bc-4323-b2d3-5c1ca0f1a091',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Construction Methods',
          'format' => NULL,
          'safe_value' => 'Construction Methods',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Construction Methods',
          'format' => NULL,
          'safe_value' => 'Construction Methods',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Construction Methods',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 108,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Collective Centres',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cc372269-a57f-4ae1-935e-13759558cd6d',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Collective Centres',
          'format' => NULL,
          'safe_value' => 'Collective Centres',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Collective Centres',
          'format' => NULL,
          'safe_value' => 'Collective Centres',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Collective Centres',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 110,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Beneficiary Communications',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd0048fc8-b03f-4176-bc06-fe0fad5ae975',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Beneficiary Communications',
          'format' => NULL,
          'safe_value' => 'Beneficiary Communications',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Beneficiary Communications',
          'format' => NULL,
          'safe_value' => 'Beneficiary Communications',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Beneficiary Communications',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 14,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Training materials',
    'description' => 'Products related to technical training for affected populations, workshops, etc.',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'd11833bc-0e62-4595-917f-ab1c1505f87c',
    'vocabulary_machine_name' => 'technical_support_design',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Training materials',
          'format' => NULL,
          'safe_value' => 'Training materials',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Training materials',
          'format' => NULL,
          'safe_value' => 'Training materials',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Products related to technical training for affected populations, workshops, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Products related to technical training for affected populations, workshops, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Products related to technical training for affected populations, workshops, etc.',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Products related to technical training for affected populations, workshops, etc.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Training materials',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 111,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562531,
          'changed' => 1422562531,
        ),
      ),
    ),
    'description_original' => 'Products related to technical training for affected populations, workshops, etc.',
  );
  $terms[] = array(
    'name' => 'Beneficiary Selection',
    'description' => 'Documentation of selection criteria for assistance prioritization of affected population',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'd5db5845-7b5c-499f-861c-b1d5ec710e61',
    'vocabulary_machine_name' => 'coordination_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Beneficiary Selection',
          'format' => NULL,
          'safe_value' => 'Beneficiary Selection',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Beneficiary Selection',
          'format' => NULL,
          'safe_value' => 'Beneficiary Selection',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Documentation of selection criteria for assistance prioritization of affected population',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation of selection criteria for assistance prioritization of affected population</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Documentation of selection criteria for assistance prioritization of affected population',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation of selection criteria for assistance prioritization of affected population</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Beneficiary Selection',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 113,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562255,
          'changed' => 1422562255,
        ),
      ),
    ),
    'description_original' => 'Documentation of selection criteria for assistance prioritization of affected population',
  );
  $terms[] = array(
    'name' => 'Camp Management',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd846ccf4-3fae-4490-b32e-90e734ce609d',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Camp Management',
          'format' => NULL,
          'safe_value' => 'Camp Management',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Camp Management',
          'format' => NULL,
          'safe_value' => 'Camp Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Camp Management',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 114,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Mental Health',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'd85163f8-0186-490a-9399-00dc651ce5fa',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Mental Health',
          'format' => NULL,
          'safe_value' => 'Mental Health',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Mental Health',
          'format' => NULL,
          'safe_value' => 'Mental Health',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Mental Health',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 115,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Settlement Planning',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd9e2592c-8c31-4ad3-a6ab-699c0356c2b8',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Settlement Planning',
          'format' => NULL,
          'safe_value' => 'Settlement Planning',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Settlement Planning',
          'format' => NULL,
          'safe_value' => 'Settlement Planning',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Settlement Planning',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 116,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Strategy',
    'description' => 'Documentation of cluster defined approaches and strategic goals',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'da80b56e-1372-472e-808e-40443b2cb8bc',
    'vocabulary_machine_name' => 'coordination_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Strategy',
          'format' => NULL,
          'safe_value' => 'Strategy',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Strategy',
          'format' => NULL,
          'safe_value' => 'Strategy',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Documentation of cluster defined approaches and strategic goals',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation of cluster defined approaches and strategic goals</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Documentation of cluster defined approaches and strategic goals',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Documentation of cluster defined approaches and strategic goals</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Strategy',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 117,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562255,
          'changed' => 1422562255,
        ),
      ),
    ),
    'description_original' => 'Documentation of cluster defined approaches and strategic goals',
  );
  $terms[] = array(
    'name' => 'IM reports and analysis',
    'description' => 'Reporting related to needs, gap, or 3W analyses usually as a table or dashboard document',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'dca64835-75f4-46a0-acf5-513570d0e8c1',
    'vocabulary_machine_name' => 'information_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'IM reports and analysis',
          'format' => NULL,
          'safe_value' => 'IM reports and analysis',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'IM reports and analysis',
          'format' => NULL,
          'safe_value' => 'IM reports and analysis',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Reporting related to needs, gap, or 3W analyses usually as a table or dashboard document',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Reporting related to needs, gap, or 3W analyses usually as a table or dashboard document</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Reporting related to needs, gap, or 3W analyses usually as a table or dashboard document',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Reporting related to needs, gap, or 3W analyses usually as a table or dashboard document</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'IM reports and analysis',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 119,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562549,
          'changed' => 1422562549,
        ),
      ),
    ),
    'description_original' => 'Reporting related to needs, gap, or 3W analyses usually as a table or dashboard document',
  );
  $terms[] = array(
    'name' => 'IEC materials',
    'description' => 'Information, Education, and Communication materials that are usually distributed as part of interventions or to affected populations',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'dd01c5f1-6dfa-4cc8-8b0a-936ff0b48050',
    'vocabulary_machine_name' => 'technical_support_design',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'IEC materials',
          'format' => NULL,
          'safe_value' => 'IEC materials',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'IEC materials',
          'format' => NULL,
          'safe_value' => 'IEC materials',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Information, Education, and Communication materials that are usually distributed as part of interventions or to affected populations',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Information, Education, and Communication materials that are usually distributed as part of interventions or to affected populations</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Information, Education, and Communication materials that are usually distributed as part of interventions or to affected populations',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Information, Education, and Communication materials that are usually distributed as part of interventions or to affected populations</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'IEC materials',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 120,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562531,
          'changed' => 1422562531,
        ),
      ),
    ),
    'description_original' => 'Information, Education, and Communication materials that are usually distributed as part of interventions or to affected populations',
  );
  $terms[] = array(
    'name' => 'Development',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'e0457000-0e06-441d-80db-6af7bcec5dd9',
    'vocabulary_machine_name' => 'response_phase',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Development',
          'format' => NULL,
          'safe_value' => 'Development',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Development',
          'format' => NULL,
          'safe_value' => 'Development',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Development',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 121,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562601,
          'changed' => 1422562601,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Clothing and Bedding',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e2f73244-8861-461d-bc50-9b774e1f0c48',
    'vocabulary_machine_name' => 'non_food_items',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Clothing and Bedding',
          'format' => NULL,
          'safe_value' => 'Clothing and Bedding',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Clothing and Bedding',
          'format' => NULL,
          'safe_value' => 'Clothing and Bedding',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Clothing and Bedding',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 15,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562691,
          'changed' => 1422562691,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Inter-Cluster Coordination',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e33af16f-d37c-4875-9c8f-6793508df352',
    'vocabulary_machine_name' => 'inter_cluster',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Inter-Cluster Coordination',
          'format' => NULL,
          'safe_value' => 'Inter-Cluster Coordination',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Inter-Cluster Coordination',
          'format' => NULL,
          'safe_value' => 'Inter-Cluster Coordination',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Inter-Cluster Coordination',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 16,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562566,
          'changed' => 1422562566,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Shelter Cluster Assessment',
    'description' => 'A report of an assessment conducted on behalf of shelter cluster partners',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'e77bdfa0-abed-40cb-ab56-6f6e043f2e8c',
    'vocabulary_machine_name' => 'assessment_monitoring_evaluation',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Shelter Cluster Assessment',
          'format' => NULL,
          'safe_value' => 'Shelter Cluster Assessment',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Shelter Cluster Assessment',
          'format' => NULL,
          'safe_value' => 'Shelter Cluster Assessment',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'A report of an assessment conducted on behalf of shelter cluster partners',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>A report of an assessment conducted on behalf of shelter cluster partners</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'A report of an assessment conducted on behalf of shelter cluster partners',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>A report of an assessment conducted on behalf of shelter cluster partners</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Shelter Cluster Assessment',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 125,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562342,
          'changed' => 1422562342,
        ),
      ),
    ),
    'description_original' => 'A report of an assessment conducted on behalf of shelter cluster partners',
  );
  $terms[] = array(
    'name' => 'Cross-Cutting Issues',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'e7a29467-4d30-4037-8fc2-c86b4e1a0955',
    'vocabulary_machine_name' => 'document_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Cross-Cutting Issues',
          'format' => NULL,
          'safe_value' => 'Cross-Cutting Issues',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Cross-Cutting Issues',
          'format' => NULL,
          'safe_value' => 'Cross-Cutting Issues',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Cross-Cutting Issues',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 147,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562671,
          'changed' => 1422562671,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Dataset',
    'description' => 'Structured data made available for sharing',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'ea80df1b-3815-4059-b0ce-e6f57cdeef9d',
    'vocabulary_machine_name' => 'information_management',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Dataset',
          'format' => NULL,
          'safe_value' => 'Dataset',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Dataset',
          'format' => NULL,
          'safe_value' => 'Dataset',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Structured data made available for sharing',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Structured data made available for sharing</p>
',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Structured data made available for sharing',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '<p>Structured data made available for sharing</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Dataset',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 126,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562549,
          'changed' => 1422562549,
        ),
      ),
    ),
    'description_original' => 'Structured data made available for sharing',
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'f1c7d9e0-e3bf-40ea-8d2c-cc6123ada4de',
    'vocabulary_machine_name' => 'inter_cluster',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Education',
          'format' => NULL,
          'safe_value' => 'Education',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Education',
          'format' => NULL,
          'safe_value' => 'Education',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Education',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 128,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562566,
          'changed' => 1422562566,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Gender',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'f4794653-28d2-44fd-b41a-a4ed6a21769b',
    'vocabulary_machine_name' => 'cross_cutting_issues',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Gender',
          'format' => NULL,
          'safe_value' => 'Gender',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Gender',
          'format' => NULL,
          'safe_value' => 'Gender',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Gender',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 18,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562583,
          'changed' => 1422562583,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Tents',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f6937478-e997-49c9-ac8c-704772e813a3',
    'vocabulary_machine_name' => 'intervention_materials',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Tents',
          'format' => NULL,
          'safe_value' => 'Tents',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Tents',
          'format' => NULL,
          'safe_value' => 'Tents',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Tents',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 129,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562617,
          'changed' => 1422562617,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Transitional Shelter',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f75613bc-427d-498d-8d0f-85c855bb3432',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Transitional Shelter',
          'format' => NULL,
          'safe_value' => 'Transitional Shelter',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Transitional Shelter',
          'format' => NULL,
          'safe_value' => 'Transitional Shelter',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Transitional Shelter',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 131,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'No legal status',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f769d279-22a8-4839-83c8-b027fdb98550',
    'vocabulary_machine_name' => 'settlement_type',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'No legal status',
          'format' => NULL,
          'safe_value' => 'No legal status',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'No legal status',
          'format' => NULL,
          'safe_value' => 'No legal status',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'No legal status',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 132,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562654,
          'changed' => 1422562654,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Camp Planning',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f8943746-b0a3-48a7-ba94-ffdfbe47ebf4',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Camp Planning',
          'format' => NULL,
          'safe_value' => 'Camp Planning',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Camp Planning',
          'format' => NULL,
          'safe_value' => 'Camp Planning',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Camp Planning',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 133,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Preparedness',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fb49a788-3b9b-4013-9159-a3df3753fb4b',
    'vocabulary_machine_name' => 'response_phase',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Preparedness',
          'format' => NULL,
          'safe_value' => 'Preparedness',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Preparedness',
          'format' => NULL,
          'safe_value' => 'Preparedness',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Preparedness',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 21,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562601,
          'changed' => 1422562601,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  $terms[] = array(
    'name' => 'Owner Driven',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fc121321-481a-4e2b-8659-53e4cd915d66',
    'vocabulary_machine_name' => 'intervention_programming',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Owner Driven',
          'format' => NULL,
          'safe_value' => 'Owner Driven',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Owner Driven',
          'format' => NULL,
          'safe_value' => 'Owner Driven',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Owner Driven',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 134,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1422562638,
          'changed' => 1422562638,
        ),
      ),
    ),
    'description_original' => NULL,
  );
  return $terms;
}
