<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_menu().
 */
function cluster_rss_menu() {
  $items['node/%node/rss/%'] = array(
    'page callback' => 'cluster_rss',
    'page arguments' => array(1, 3),
    'delivery callback' => 'cluster_rss_deliver',
    'file' => 'cluster_rss.inc',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function cluster_rss_theme($existing, $type, $theme, $path) {
  return array(
    'cluster_rss' => array(
      'variables' => array(
        'items' => NULL,
        'date' => NULL,
        'title' => NULL,
        'path' => NULL,
        'type' => NULL,
      ),
      'template' => '/templates/response_rss',
    ),
  );
}
