<?php

//Shelter brand guidelines colors
const CLUSTER_CHART_COLOR_SHELTER_RED = '#7f1416';
const CLUSTER_CHART_COLOR_SHELTER_GREY = '#575757';
const CLUSTER_CHART_COLOR_SHELTER_LIGHT_BLUE = '#cdd6db';
const CLUSTER_CHART_COLOR_SHELTER_DARK_BLUE = '#688394';

//Shelter chart guidelines colors
const CLUSTER_CHART_COLOR_ACCENT_YELLOW = 'rgba(255,177,0,1)';
const CLUSTER_CHART_COLOR_ACCENT_GREEN = 'rgb(101,182,48)';
const CLUSTER_CHART_COLOR_ACCENT_RED = 'rgb(252,0,0)';
const CLUSTER_CHART_COLOR_ACCENT_BLUE = 'rgb(22,135,203)';
const CLUSTER_CHART_COLOR_ACCENT_DARK_BLUE = 'rgb(4,49,76)';

// Shades
const CLUSTER_CHART_COLOR_SHELTER_RED_SHADE1 = '#a05a49';
const CLUSTER_CHART_COLOR_SHELTER_RED_SHADE2 = '#cca496';

function cluster_chart_include_lib() {
  drupal_add_js(drupal_get_path('module', 'cluster_chart') . '/js/lib/Chart.min.js', ['group' => JS_LIBRARY]);
  drupal_add_js(drupal_get_path('module', 'cluster_chart') . '/js/lib/Chart.PieceLabel.js', ['group' => JS_LIBRARY]);
  drupal_add_js(drupal_get_path('module', 'cluster_chart') . '/js/charts.js');
}

/**
 * Implements hook_theme().
 */
function cluster_chart_theme($existing, $type, $theme, $path) {
  return [
    'cluster_chart_pie' => [
      'variables' => [
        'extra_css_classes' => NULL,
        'data' => NULL,
        'labels' => NULL,
        'colors' => NULL,
        'options' => NULL,
      ],
    ],
    'cluster_chart_hbar' => [
      'variables' => [
        'extra_css_classes' => NULL,
        'data' => NULL,
        'labels' => NULL,
        'colors' => NULL,
        'options' => NULL,
      ],
    ],
  ];
}

function theme_cluster_chart_pie($variables) {
  $html_id = drupal_html_id('cluster_chart');

  cluster_chart_include_lib();

  drupal_add_js(['cluster_chart' => ['type_pie' => [$html_id => $variables]]], 'setting');

  $extra_css_classes = (array) ($variables['extra_css_classes'] ?: []);
  return '<div' . drupal_attributes(['class' => array_merge(['cluster-chart-wrapper'], $extra_css_classes)]) . '>'.
    '<canvas' . drupal_attributes(['id' => $html_id]) . "></canvas></div>\n";
}

function theme_cluster_chart_hbar($variables) {
  $html_id = drupal_html_id('cluster_chart');

  cluster_chart_include_lib();

  drupal_add_js(['cluster_chart' => ['type_hbar' => [$html_id => $variables]]], 'setting');

  $extra_css_classes = (array) ($variables['extra_css_classes'] ?: []);
  return '<div' . drupal_attributes(['class' => array_merge(['cluster-chart-wrapper'], $extra_css_classes)]) . '>'.
    '<canvas' . drupal_attributes(['id' => $html_id]) . "></canvas></div>\n";
}

function cluster_chart_number_format($number) {
  if ($number < 700000)
    return number_format($number);

  return sprintf('%.1f M', $number / 1000000);
}

function cluster_chart_png_hbar($data, $labels, $colors, $width, $height, $cache_filename = NULL) {
  // TODO: implement file caching

  require_once drupal_get_path('module', 'cluster_chart') . '/jpgraph/src/jpgraph.php';
  require_once drupal_get_path('module', 'cluster_chart') . '/jpgraph/src/jpgraph_bar.php';

  $graph = new Graph($width, $height);
  $graph->SetScale("textlin");

  $maxLabelWidth = max(array_map('strlen', $labels)) * 9;

  $graph->Set90AndMargin(50 + $maxLabelWidth,60,40,20); // "horizontal" bar chart
  $graph->SetTickDensity(TICKD_VERYSPARSE);
  $graph->xaxis->SetTickLabels($labels);
  $graph->xaxis->SetFont(FF_DV_SANSSERIF,FS_NORMAL,14);
  $graph->yaxis->SetFont(FF_DV_SANSSERIF,FS_NORMAL,14);
  $graph->xaxis->SetLabelMargin(10);
  $graph->xaxis->SetLabelAlign('right','center');
  $graph->yaxis->scale->SetGrace(5);
  $graph->yaxis->scale->ticks->SetFormatCallback('cluster_chart_number_format');
  $graph->ygrid->SetFill(false);

  $bplot = new BarPlot($data);
  $graph->Add($bplot);

  $bplot->SetWeight(0); // removes border around bars
  $bplot->SetFillColor($colors);
  $bplot->SetWidth(0.8);
  $bplot->value->SetFont(FF_DV_SANSSERIF,FS_BOLD,12);

  $graph->Stroke();
  drupal_exit();
}

function cluster_chart_png_pie($data, $labels, $colors, $width, $height, $cache_filename = NULL) {
  // TODO: implement file caching

  require_once drupal_get_path('module', 'cluster_chart') . '/jpgraph/src/jpgraph.php';
  require_once drupal_get_path('module', 'cluster_chart') . '/jpgraph/src/jpgraph_pie.php';

  $graph = new PieGraph($width, $height);

  $plot = new PiePlot($data);

  $graph->Add($plot);

  $plot->value->Show(false);
  $plot->SetStartAngle(90);
  $plot->SetSize(0.47);
  $plot->SetCenter(0.5,0.5);
  $plot->SetSliceColors($colors);
  $plot->SetLabelPos(.6);

  $graph->Stroke();
  drupal_exit();
}
