<?php

include_once 'cluster_assessment.features.inc';
include_once 'cluster_assessment.pathauto.inc';

/**
 * Implements hook_menu().
 */
function cluster_assessment_menu() {
  return [
    'node/%node/data-collection' => [
      'title' => 'Data collection',
      'page callback' => 'cluster_assessment_all',
      'page arguments' => [1],
      'access callback' => 'og_is_group',
      'access arguments' => [0, 1],
      'title callback' => '_cluster_assessment_title_callback',
      'title arguments' => [1],
      'type' => MENU_CALLBACK,
    ],
  ];
}

/**
 * @param $node
 * @return array|int
 */
function cluster_assessment_all($node) {
  $manager = GroupContentManager::getInstance($node);

  $nids = [];
  if (module_exists('cluster_webform'))
    $nids = array_merge($nids, $manager->getWebforms(TRUE));
  if (module_exists('cluster_kobo'))
    $nids = array_merge($nids, $manager->getKoboForms());
  if (!$nids)
    return MENU_NOT_FOUND;

  $nodes = node_load_multiple($nids);

  $show_templates = variable_get('cluster_og_resources_id') == $node->nid;

  return [
    '#theme' => 'links',
    '#attributes' => ['class' => ['data-collection-list']],
    '#links' => array_map(function($node) use ($show_templates) {
      $body_items = field_get_items('node', $node, 'field_body');

      if ($body_items && $body_items[0]['safe_value'])
        $html_title = t('<h4><i class="fas fa-edit"></i> @title</h4><p>@description</p>', [
          '@title' => $node->title,
          '@description' => $body_items[0]['value'],
        ]);
      else
        $html_title = t('<h4><i class="fas fa-edit"></i> @title</h4>', ['@title' => $node->title]);

      return [
        'title' => $html_title,
        'html' => TRUE,
        'href' => $show_templates ? 'node/'.$node->nid.'/export' : 'node/'.$node->nid,
      ];
    }, $nodes),
  ];
}

/**
 * Menu title callback.
 *
 * @see _cluster_docs_title_callback() (mostly copied from there)
 */
function _cluster_assessment_title_callback($node) {
  if (variable_get('cluster_og_resources_id') == $node->nid)
    return t('Data collection templates');
  else
    return $node->title . ' - ' . t('Data collection');
}

function cluster_assessment_total_count($gid) {
  $group = node_load($gid);
  $manager = GroupContentManager::getInstance($group);
  $ret = 0;

  if (module_exists('cluster_webform'))
    $ret += $manager->getWebformsCount(TRUE);
  if (module_exists('cluster_kobo'))
    $ret += $manager->getKoboFormsCount();

  return $ret;
}

function cluster_assessment_is_group_forms_page() {
  $router_item = menu_get_item(current_path());

  if ($router_item && isset($router_item['path']))
    return $router_item['path'] === 'node/%/assessment-forms';

  return FALSE;
}
