<?php
/**
 * @file
 * Code for the Cluster Content feature.
 */

include_once 'cluster_content.features.inc';

/**
 * Implements hook_admin_paths().
 */
function cluster_content_admin_paths() {
  return array(
    'node/*/content' => TRUE,
  );
}

/**
 * Implements hook_restws_format_info_alter().
 */
function cluster_content_restws_format_info_alter(&$format_info) {
  $format_info['json']['class'] = 'Drupal\cluster_content\RestWSFormat\ClusterFormatJSON';
}
