<?php

include_once 'cluster_api.features.inc';

const CLUSTER_API_FOLLOWER_ROLE_NAME = 'follower';

/**
 * Implements hook_services_resources().
 */
function cluster_api_services_resources() {
  return [
    'get-objects' => [
      'operations' => [
        'create' => [ // This isn't "creating" anything. REST verbs just suck.
          'help' => 'Load objects, including any related objects',
          'file' => [
            'type' => 'inc',
            'module' => 'cluster_api',
            'name' => 'resources/get_objects',
          ],
          'callback' => '_cluster_api_get_objects',
          'args' => [
            [
              'name' => 'requests',
              'optional' => FALSE,
              'source' => 'data',
              'type' => 'array',
              'description' => 'A list of object ids (and their types) to load.',
            ],
          ],
          'access callback' => 'user_access',
          'access arguments' => ['access content'],
          'access arguments append' => FALSE,
        ],
      ],
    ],
    'follow' => [
      'operations' => [
        'create' => [
          'help' => 'Follow a group',
          'file' => [
            'type' => 'inc',
            'module' => 'cluster_api',
            'name' => 'resources/follow',
          ],
          'callback' => '_cluster_api_follow',
          'args' => [
            [
              'name' => 'id',
              'optional' => FALSE,
              'source' => ['path' => 0],
              'type' => 'int',
              'description' => 'The id of the group node to follow',
            ],
          ],
          'access callback' => 'user_access',
          'access arguments' => ['access content'],
          'access arguments append' => FALSE,
        ],
        'delete' => [
          'help' => 'Un-follow a group',
          'file' => [
            'type' => 'inc',
            'module' => 'cluster_api',
            'name' => 'resources/follow',
          ],
          'callback' => '_cluster_api_unfollow',
          'args' => [
            [
              'name' => 'id',
              'optional' => FALSE,
              'source' => ['path' => 0],
              'type' => 'int',
              'description' => 'The id of the group node to un-follow',
            ],
          ],
          'access callback' => 'user_access',
          'access arguments' => ['access content'],
          'access arguments append' => FALSE,
        ],
      ],
    ],
  ];
}

/**
 * @param string $group_bundle e.g. "geographic_region"
 *
 * @return int
 * @throws \Exception
 */
function _cluster_api_get_follower_role_by_bundle($group_bundle) {
  $roles = array_flip(og_roles('node', $group_bundle));
  if (!array_key_exists(CLUSTER_API_FOLLOWER_ROLE_NAME, $roles))
    throw new Exception('Group bundle does not have follower role: ' . $group_bundle);
  return $roles[CLUSTER_API_FOLLOWER_ROLE_NAME];
}
