<?php

function partials_theme() {
  return array(
    'partial' => array(
      'variables' => array(),
      'template' => 'partial',
    ),
  );
}

function template_preprocess_partial(&$variables) {
  $key = $variables['key'];
  $variables['theme_hook_suggestion'] = 'partial__' . $key;
  $preprocess = 'partial_' . $key . '_preprocess';
  if (function_exists($preprocess)) {
    $preprocess($variables);
  }
}

function partial($key, $variables) {
  $variables['key'] = $key;
  return theme('partial', $variables);
}