<?php
/**
 * @file
 * Code for the Cluster Events feature.
 */

include_once 'cluster_events.features.inc';
include_once 'cluster_events.pathauto.inc';

const CLUSTER_EVENTS_PER_PAGE = 10;

/**
 *  Implements hook_menu().
 */
function cluster_events_menu() {
  $items['node/%/events'] = array(
    'title' => 'events',
    'title callback' => '_cluster_events_title_callback',
    'title arguments' => array(1),
    'page callback' => 'cluster_events_all',
    'page arguments' => array(1),
    'access callback' => 'og_is_group',
    'access arguments' => array(0, 1),
    'type' => MENU_CALLBACK,
  );

  $items['events'] = array(
    'title' => 'All events',
    'page callback' => 'cluster_events_all',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu title callback.
 */
function _cluster_events_title_callback($nid) {
  global $language;
  $title = t('Events');
  if (! is_numeric($nid)) {
    return $title;
  }

  try {
    // @TODO manage multilinigual loading of entities.
    $wrapper = entity_metadata_wrapper('node', node_load($nid), array('langcode' => LANGUAGE_NONE));
    return $wrapper->label();
  }
  catch (EntityMetadataWrapperException $exc) {
    _log_entity_metadata_wrapper_error($exc, 'cluster_context');
  }
  return $title;
}

/**
 * Page callback, lists of events using Search API.
 * @param $nid, if present, limit events that are part of group id audience.
 * @return Render array
 */
function cluster_events_all($nid) {
  module_load_include('inc', 'cluster_events', 'cluster_events.helpers');
  $all_events = !_cluster_events_all_events_only_upcoming_events();

  $order = $all_events ? 'DESC' : 'ASC';

  $date = new DateTime('12am today');
  $today = $date->format('Y-m-d 00:00:00');

  // Filter by event date with entity field query.
  $filter_by_date = new EntityFieldQuery();
  $filter_by_date->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldOrderBy('field_recurring_event_date2', 'value', $order);

  $filter_by_date_count = new EntityFieldQuery();
  $filter_by_date_count->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldOrderBy('field_recurring_event_date2', 'value', $order)
    ->count();

  if (!$all_events) {
    $filter_by_date->fieldCondition('field_recurring_event_date2', 'value', $today, '>=');
    $filter_by_date_count->fieldCondition('field_recurring_event_date2', 'value', $today, '>=');
  }

  if ($nid) {
    $filter_by_date->fieldCondition('og_group_ref', 'target_id', $nid);
    $filter_by_date_count->fieldCondition('og_group_ref', 'target_id', $nid);
  }

  $number_of_results = $filter_by_date_count->execute();

  $offset = pager_find_page() * CLUSTER_EVENTS_PER_PAGE;
  $filter_by_date->range($offset, CLUSTER_EVENTS_PER_PAGE);

  // Execute query to filter by event date.
  $query_date_filter_results = $filter_by_date->execute();

  pager_default_initialize($number_of_results, CLUSTER_EVENTS_PER_PAGE);

  if (empty($query_date_filter_results['node'])) {
    $content['events_toggle_button'] = _cluster_events_add_toggle_button(TRUE);
    $content['events']['#markup'] = t('No events scheduled at the moment.');
  }
  else {
    $content = array(
      "#theme" => 'cluster_og_all_events',
      '#events' => array(),
    );
    $nids = array_keys($query_date_filter_results['node']);
    $content['#events'] = cluster_events_format_list($nids);
  }

  $ret['content'] = $content;
  $ret['pager'] = array(
    '#theme' => 'pager',
  );

  return $ret;
}

/**
 * Get upcoming events.
 *
 * @return bool|string
 */
function cluster_events_upcoming() {
  return cluster_events_get_events('>', 'ASC');
}

/**
 * Get previous events.
 *
 * @return bool|string
 */
function cluster_events_previous() {
  return cluster_events_get_events('<', 'DESC');
}

/**
 * Get event nodes.
 *
 * @param string $operator
 *   The operator to use within the date field condition (i.e. less or greater
 *   than the specified date.
 * @param string $order
 *   The order to sort the results - e.g. 'ASC' or 'DESC'.
 *
 * @return bool|string
 */
function cluster_events_get_events($operator = '>', $order = 'ASC') {
  $query = new EntityFieldQuery();
  $results = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->fieldCondition('field_recurring_event_date2', 'value', date('Y-m-d'), $operator)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldOrderBy('field_recurring_event_date2', 'value', $order)
    ->range(0, 3)
    ->execute();

  if (!isset($results['node'])) {
    return FALSE;
  }

  $nids = array_keys($results['node']);

  $entities = entity_load('node', $nids);
  $events = array();
  foreach ($entities as $entity) {
    $events[] = cluster_events_format_upcoming($entity->nid);
  }

  $is_previous = $operator === '<';

  return theme('cluster_og_upcoming_events', array(
    'events' => $events,
    'is_previous_events' => $is_previous,
    'all_events_link' => '/events',
    'global_events_link' => array(
      '#type' => 'link',
      '#href' => 'geographic-region/global/events',
      '#title' => 'See Global Events',
    ),
    'previous_events_link' => '',
  ));
}

function cluster_events_format_upcoming($nid) {
  $node = node_load($nid);
  if (!$node || $node->type != 'event') {
    return FALSE;
  }

  try {
    /** @var EntityDrupalWrapper $wrapper */
    $wrapper = entity_metadata_wrapper('node', $node);

    // Render the date as per the teaser field display setting.
    $date = $wrapper->get('field_recurring_event_date2')->value();
    $date = strtotime($date[0]['value']);
    $date = format_date($date, 'custom', 'H:i - Y m d');

    $geo = _cluster_events_get_geocoordinates_from_address_field($wrapper->field_postal_address->value());

    $map_link = l(t('map'), 'https://www.google.ca/maps/place/' . $geo['lat'] . ',' . $geo['lon'] . '/@' . $geo['lat'] . ',' . $geo['lon'] . ',15z', array(
      'attributes' => array(
        'target' => '_blank',
      )
    ));

    // Get contact(s).
    $contacts = $wrapper->field_event_contact->value();
    $contact_list = cluster_events_get_contact_list($contacts);

    $static_map = FALSE;
    if (!empty($geo)) {
      $static_map_url = 'http://maps.googleapis.com/maps/api/staticmap?center=' . $geo['lat'] . ',' . $geo['lon'] . '&zoom=15&scale=1&size=300x200&maptype=roadmap&format=png&visual_refresh=true&markers=size:small|color:0x000000|label:1|' . $geo['lat'] . ',' . $geo['lon'];
      $static_map_description = 'Map to ' . $wrapper->title->value();
      $static_map = theme('image', array(
        'path' => $static_map_url,
        'alt' => t($static_map_description),
        'title' => t($static_map_description),
      ));
    }

    // Add a link to the response.
    $response_link = l(
      $wrapper->get('og_group_ref')->label(),
      'node/' . $wrapper->getIdentifier()
    );

    $response = t('Response: !response_link', array(
      '!response_link' => $response_link
    ));

    return array(
      'date' => $date,
      'title' => $wrapper->title->value(),
      'link' => l($wrapper->title->value(), 'node/' . $node->nid),
      'location' => field_view_field('node', $node, 'field_postal_address', 'teaser'),
      'map_link' => $map_link,
      'static_map' => FALSE,
      'contact' => $contact_list,
      'ical' => l('iCal', sprintf('node/%d/%s/ical/addtocal.ics', $node->nid, 'field_recurring_event_date2')),
      'response' => $response,
    );
  }
  catch (EntityMetadataWrapperException $exception) {
    _log_entity_metadata_wrapper_error($exception, 'cluster_events');
  }
}

function cluster_events_format_list($nids) {
  $events = array();
  foreach ($nids as $nid) {
    $node = node_load($nid);
    if (!$node || $node->type != 'event') {
      return FALSE;
    }

    try {
      $wrapper = entity_metadata_wrapper('node', $node);
      $value = $wrapper->field_recurring_event_date2->value();
      $event_date = $value[0];
      $current_date = time();
      $is_future = $event_date > $current_date ? TRUE : FALSE;
      $is_past = !$is_future;

      // Render the date as per the teaser field display setting.
      $date = field_view_field('node', $node, 'field_recurring_event_date2', 'teaser');

      $geo = _cluster_events_get_geocoordinates_from_address_field($wrapper->field_postal_address->value());

      $map_url = 'https://www.google.ca/maps/place/' . $geo['lat'] . ',' . $geo['lon'] . '/@' . $geo['lat'] . ',' . $geo['lon'] . ',15z';
      $map_link = l(t('map'), $map_url, array(
        'attributes' => array(
          'target' => '_blank',
        )
      ));

      // Get contact(s).
      $contacts = $wrapper->field_event_contact->value();
      $contact_list = cluster_events_get_contact_list($contacts);

      $static_map = cluster_events_create_map_with_link($geo, $wrapper->title->value());

      $events[] = array(
        'is_future' => $is_future,
        'is_past' => $is_past,
        'date' => $date,
        'title' => t($wrapper->title->value()),
        'link' => l($wrapper->title->value(), 'node/' . $node->nid),
        'location' => field_view_field('node', $node, 'field_postal_address', 'teaser'),
        'map_link' => $map_link,
        'static_map' => $static_map,
        'contact' => $contact_list,
        'description' => field_view_field('node', $node, 'body', 'teaser'),
      );
    }
    catch (EntityMetadataWrapperException $exception) {
      _log_entity_metadata_wrapper_error($exception, 'cluster_events');
    }
  }
  return $events;
}

/**
 * Implements hook_preprocess_node().
 */
function cluster_events_preprocess_node(&$variables) {
  if ($variables['type'] == 'event') {
    $variables['static_map'] = FALSE;
    $variables['map_link'] = FALSE;
    try {
      $wrapper = entity_metadata_wrapper('node', $variables['node']);
      $geo = _cluster_events_get_geocoordinates_from_address_field($wrapper->field_postal_address->value());

      // Get contact(s).
      $contacts = $wrapper->field_event_contact->value();
      $contact_list = cluster_events_get_contact_list($contacts);

      // Replace the field with our custom contact list.
      if ($contact_list) {
        $variables['content']['field_event_contact'] = array(
          '#weight' => 2,
          '#markup' => $contact_list,
          '#prefix' => '<div class="field"><div class="field-label">Contact:&nbsp;</div>',
          '#suffix' => '</div></div>'
        );
      }

      // Static map image.
      $variables['static_map'] = cluster_events_create_map_with_link($geo, $wrapper->title->value());
    }
    catch (EntityMetadataWrapperException $exception) {
      _log_entity_metadata_wrapper_error($exception, 'cluster_events');
    }
  }
}

/**
 * Returns a map linking back to the Google maps.
 */
function cluster_events_create_map_with_link($geo = NULL, $map_title = '') {
  $static_map = FALSE;
  if (!empty($geo)) {
    $map_url = 'https://www.google.ca/maps/place/' . $geo['lat'] . ',' . $geo['lon'] . '/@' . $geo['lat'] . ',' . $geo['lon'] . ',15z';
    $static_map_url = 'http://maps.googleapis.com/maps/api/staticmap?center=' . $geo['lat'] . ',' . $geo['lon'] . '&zoom=15&scale=1&size=300x200&maptype=roadmap&format=png&visual_refresh=true&markers=size:small|color:0x000000|label:1|' . $geo['lat'] . ',' . $geo['lon'];
    $static_map_description = t('Map to ') . $map_title;
    $static_map = theme('image', array(
      'path' => $static_map_url,
      'alt' => $static_map_description,
      'title' => $static_map_description,
    ));
    $static_map = l($static_map, $map_url, array('html' => TRUE, 'attributes' => array('target' => '_blank')));
  }
  return $static_map;
}

/**
 * Returns a list of contact links.
 */
function cluster_events_get_contact_list($contacts = FALSE) {
  $contact_list = FALSE;

  if (!empty($contacts)) {
    $contact_email = '';
    $last_contact = count($contacts) - 1;

    // Get all the contacts and email address.
    foreach ($contacts as $index => $contact) {
      $separator = ", ";
      if ($index == $last_contact) {
        $separator = '';
      }

      if (empty($contact->field_email)) {
        $contact_list .= $contact->title . $separator;
        continue;
      }

      $contact_name = $contact->title;
      $contact_email = $contact->field_email['und']['0']['email'];

      $contact_link = '';
      $options = array();
      $contact_link = l(t($contact_name), 'mailto:' . $contact_email, $options, array('attributes' => array('class' => array('contact-link'))));

      $contact_list .= $contact_link . $separator;
    }
  }
  return $contact_list;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function cluster_events_preprocess_partial(&$variables) {
  switch ($variables['name']) {
    case 'all_events':
      module_load_include('inc', 'cluster_events', 'cluster_events.helpers');

      $all_events = _cluster_events_all_events_only_upcoming_events();
      $button = _cluster_events_add_toggle_button($all_events);

      $variables['events_toggle_button'] = render($button);
      break;
  }
}

/**
 * Implements hook_field_access().
 */
function cluster_events_field_access($op, $field, $entity_type, $entity, $account) {
  if ($op != 'view' && $field['field_name'] == 'field_recurring_event_date') {
    return FALSE;
  }
}

/**
 * Add a button to toggle between all events and only upcoming events.
 *
 * @var boolean $all_events
 *   (optional) Whether to show all events. Defaults to FALSE.
 *
 * @return array
 */
function _cluster_events_add_toggle_button($all_events = FALSE) {
  $options = array();

  if ($all_events) {
    $options['query']['all'] = NULL;
  }

  $path = url(current_path(), $options);
  $title = t('@', array('@' => $all_events ? 'View all events' : 'View only upcoming events'));

  return array(
    '#markup' => sprintf('<a href="%s">%s</a>', $path, $title),
    '#prefix' => '<p class="past-events-link">',
    '#suffix' => '</p>',
    '#weight' => -1,
  );
}

/**
 * Implements hook_TYPE_alter().
 */
function cluster_events_toggle_optional_fields_overridden_fields_alter(array &$fields) {
  $fields['node']['event'] = array(
    'field_event_contact' => TRUE,
    'field_postal_address' => TRUE,
    'field_recurring_event_date2' => TRUE,
    'language' => FALSE,
  );

  global $user;
  $fields['node']['event']['og_group_ref'] = shelter_base_get_group_count_for_user($user->uid) != 1;
}

/**
 * Implements hook_entity_info_alter().
 */
function cluster_events_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['ical'] = array(
    'label' => t('iCal'),
    'custom settings' => TRUE,
  );
}

/**
 * Parse longitude and lattitude out of addressfield.
 */
function _cluster_events_get_geocoordinates_from_address_field($addressfield_values) {
  $data = unserialize($addressfield_values['data']);
  return ['lon' => $data['longitude'], 'lat' => $data['latitude']];
}