<?php
/**
 * @file
 * Handles all functionality related to navigation.
 */

/**
 *  Implements hook_preprocess_page().
 */
function cluster_nav_preprocess_page(&$variables) {
  $node = menu_get_object();

  if (!$node) {
    return;
  }

  $group_page_content = NULL;

  if (og_is_group('node', $node)) {
    $group_page_content = GroupContentManager::getInstance($node);
  } elseif ($node->type == 'discussion') {
    dpm($node, 'discussion node!');
  }

  if ($group_page_content) {
    $variables['dashboard_menu'] = $group_page_content->getDashboardMenu();
  }
}

/**
 *  Implements hook_theme().
 */
function cluster_nav_theme($existing, $type, $theme, $path) {
  return array(
    'cluster_nav' => array(
      'variables' => array(
        'items' => array(),
        'secondary' => array(),
      ),
      'template' => 'theme/cluster_nav',
    ),
  );
}