<?php
/**
 * @file
 * Code for the cluster_user feature.
 */

include_once 'cluster_user.features.inc';
/**
 * @file
 * Feature module which hanldes user parameters.
 */

/**
 * Implements hook_action_info().
 */
function cluster_user_action_info() {
  return array(
    'cluster_user_block_account' => array(
      'type' => 'user',
      'label' => t('Block user account'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
    'cluster_user_unblock_account' => array(
      'type' => 'user',
      'label' => t('Unblock user account'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}

/**
 * Block the user account, set status to 0.
 */
function cluster_user_block_account(&$entity, $context) {
  $entity->status = 0;
}

/**
 * Unblock the user account, set status to 1.
 */
function cluster_user_unblock_account(&$entity, $context) {
  $entity->status = 1;
}

/**
 * Implements hook_views_default_views_alter().
 */
function cluster_user_views_default_views_alter(&$views) {
  // Modify the user admin_views to include our custom actions.
  if (isset($views['admin_views_user'])) {
    $handler = &$views['admin_views_user']->display['default']->handler;
    $vbo = &$handler->display->display_options['fields']['views_bulk_operations']['vbo_operations'];
    $vbo['action::cluster_user_block_account'] = array(
      'selected' => 1,
      'postpone_processing' => 0,
      'skip_confirmation' => 0,
      'skip_permission_check' => 0,
      'override_label' => 0,
      'label' => '',
    );
    $vbo['action::cluster_user_unblock_account'] = array(
      'selected' => 1,
      'postpone_processing' => 0,
      'skip_confirmation' => 0,
      'skip_permission_check' => 0,
      'override_label' => 0,
      'label' => '',
    );
  }
}

/**
 * Implements hook_menu().
 */
function cluster_user_menu() {
  $items['user/%user/logout'] = array(
    'title' => t('Log out'),
    'page callback' => 'user_logout',
    'page arguments' => array(1),
    'access callback' => 'cluster_user_logout_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1000,
    'file' => 'user.pages.inc',
    'file path' => drupal_get_path('module', 'user'),
  );

  $items['user/me/edit'] = [
    'title' => 'Redirecting to user edit page',
    'access callback' => TRUE,
    'page callback' => 'cluster_user_edit_redirect',
    'type' => MENU_CALLBACK,
  ];

  $items['admin/config/shelter/registration'] = [
    'title' => t('User registration settings'),
    'description' => t('Rules for preventing users from registering on the site'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['cluster_user_registration_settings_form'],
    'access arguments' => ['administer site configuration'],
    'file' => 'cluster_user.forms.inc',
  ];

  return $items;
}

function cluster_user_logout_access($current_user) {
  global $user;
  return user_is_logged_in() && $user->uid == $current_user->uid;
}

function cluster_user_edit_redirect() {
  global $user;

  if (isset($_GET['destination'])) {
    $destination = $_GET['destination'];
    unset($_GET['destination']);
  }

  if ($user->uid) {
    drupal_goto('user/'.$user->uid.'/edit', [
      'query' => ['destination' => $destination],
    ]);
  } else
    drupal_goto('user/login', [
      'query' => ['destination' => 'user/me/edit'],
    ]);
}

/**
 * Implements hook_custom_theme().
 */
function cluster_user_custom_theme() {
  if (arg(0) === 'user' && arg(2) === 'edit') {
    return variable_get('theme_default');
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function cluster_user_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'custom_theme' && isset($implementations['cluster_user'])) {
    $group = $implementations['cluster_user'];
    unset($implementations['cluster_user']);
    $implementations['cluster_user'] = $group;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cluster_user_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $form['#pre_render'][] = '_cluster_user_register_form_pre_render';

  $groups = ['group_profile', 'group_preferences', 'group_user', 'group_groups', 'group_notifications'];
  $form['#group_children'] = array_filter($form['#group_children'], function($current_group) use ($groups) {
    return !in_array($current_group, $groups);
  });

  $form['#validate'][] = 'cluster_user_user_register_form_validate';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cluster_user_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['#pre_render'][] = '_cluster_user_edit_form_pre_render';

  $form['picture']['picture_delete']['#access'] = FALSE;
  unset($form['picture']['picture_upload']['#description']);

  // Fancy "groups" tableselect field so users can remove themselves from groups.

  $uid = $form['#user']->uid;
  $options = [];
  $default_value = [];

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'og_membership')
    ->propertyCondition('group_type', 'node')
    ->propertyCondition('etid', $uid)
    ->propertyCondition('entity_type', 'user')
    ->execute();

  $gids = [];
  $default_value = [];
  if (!empty($result['og_membership'])) {
    $memberships = og_membership_load_multiple(array_keys($result['og_membership']));
    foreach ($memberships as $membership) {
      $gid = $membership->gid;
      $gids[] = $gid;
      $default_value[$gid] = TRUE;
    }
  }

  $global_id = variable_get('cluster_og_global_id');
  if ($global_id && !in_array($global_id, $gids))
    $gids[] = $global_id;

  foreach ($gids as $gid) {
    $group = node_load($gid);
    $display = GroupDisplayProvider::getDisplayProvider($group);
    $roles = array_filter(
      og_get_user_roles('node', $gid, $uid),
      function($role) {
        return !in_array($role, [OG_AUTHENTICATED_ROLE, OG_ANONYMOUS_ROLE]);
      }
    );

    $options[$gid] = [
      'name' => l($group->title, 'node/'.$group->nid, [
        'attributes' => ['target' => '_blank'],
      ]),
      'type' => $display->getGroupTypeLabel(),
      'role' => implode(', ', $roles),
      'type_machine_name' => $group->type,
      'gid' => $group->nid,
    ];
  }

  $weights_by_type = [
    'geographic_region' => 0,
    'response' => 1,
    'working_group' => 2,
    'hub' => 3,
    'strategic_advisory' => 4,
    'community_of_practice' => 5,
  ];

  uasort($options, function($a, $b) use ($global_id, $weights_by_type) {
    // Global group always comes first
    if ($a['gid'] === $global_id)
      return -1;
    if ($b['gid'] === $global_id)
      return 1;

    // Now sort by group type
    if ($a['type_machine_name'] !== $b['type_machine_name']) {
      if (!isset($weights_by_type[$a['type_machine_name']]))
        $weights_by_type[$a['type_machine_name']] = 100;
      if (!isset($weights_by_type[$b['type_machine_name']]))
        $weights_by_type[$b['type_machine_name']] = 100;
      return $weights_by_type[$a['type_machine_name']] - $weights_by_type[$b['type_machine_name']];
    }

    // Finally, sort alphabetically
    return strcmp($a['name'], $b['name']);
  });

  $header = array(
    'name' => t('Name'),
    'type' => t('Type'),
    'role' => t('Role'),
  );

  $form['cluster_groups'] = array(
    '#type' => 'tableselect',
    '#suffix' => '<p><em>' . t('Uncheck any group to un-follow.') . '</em></p>',
    '#header' => $header,
    '#options' => $options,
    '#multiple' => TRUE,
    '#default_value' => $default_value,
  );

  $form['#group_children']['cluster_groups'] = 'group_groups';
  $form['#submit'][] = 'cluster_user_edit_groups_submit';

  $form['#attached']['js'][] = drupal_get_path('module', 'cluster_user') . '/js/user-edit.js';
}

function cluster_user_edit_groups_submit($form, &$form_state) {
  $user = $form['#user'];

  $groups_input = $form_state['values']['cluster_groups'];
  $gids_to_add = array_keys(array_filter($groups_input));
  $gids_to_remove = array_keys(array_filter($groups_input, function($value) {return !$value;}));

  foreach ($gids_to_add as $gid) {
    $membership = og_get_membership('node', $gid, 'user', $user->uid);
    if (!$membership)
      cluster_og_follow($user, node_load($gid));
  }

  $membership_ids = [];
  foreach ($gids_to_remove as $gid) {
    $membership = og_get_membership('node', $gid, 'user', $user->uid);
    if ($membership)
      $membership_ids[] = $membership->identifier();
  }
  if (!empty($membership_ids))
    og_membership_delete_multiple($membership_ids);
}

function _cluster_user_edit_form_pre_render($elements) {
  unset($elements['group_tabs']['group_preferences']['timezone']['#theme_wrappers']);
  unset($elements['group_tabs']['group_preferences']['locale']['#theme_wrappers']);
  unset($elements['group_tabs']['group_groups']['og_user_node1']['und']['#theme_wrappers']);

  unset($elements['group_tabs']['group_preferences']['timezone']['timezone']['#description']);
  unset($elements['group_tabs']['group_preferences']['locale']['language']['#description']);

  return $elements;
}

function _cluster_user_register_form_pre_render($elements) {
  unset($elements['timezone']['#theme_wrappers']);
  unset($elements['locale']['#theme_wrappers']);
  unset($elements['timezone']['timezone']['#description']);
  unset($elements['locale']['language']['#description']);

  return $elements;
}

/**
 * Implements hook_user_insert().
 *
 * Auto-follows the "Global" group.
 */
function cluster_user_user_insert(&$edit, $account, $category) {
  if ($global_id = variable_get('cluster_og_global_id')) {
    cluster_og_follow($account, node_load($global_id));
  }
}

/**
 * Implements hook_user_cancel_methods_alter().
 */
function cluster_user_user_cancel_methods_alter(&$methods) {
  if (isset($methods['user_cancel_delete']))
    // For this site we never want to bulk-delete all the content created by a user.
    unset($methods['user_cancel_delete']);

  if (isset($methods['user_cancel_block_unpublish']))
    // Let's disallow the method that bulk-unpublishes the content too.
    unset($methods['user_cancel_block_unpublish']);
}

/**
 * Returns true if any of this is true:
 *
 * 1. the user has the "trusted" or "admin" roles
 * 2. the user has any published content (nodes or comments)
 * 3. the user is a group admin on any group
 *
 * @param object $user
 *
 * @return bool
 */
function cluster_user_is_trusted($user) {
  if (!$user || !$user->uid)
    return FALSE;

  if (!$user->status)
    return FALSE; // user is blocked

  // 1.

  $roles = (array) $user->roles;
  if (in_array('administrator', $roles) || in_array('trusted user', $roles))
    return TRUE;

  // 2.

  $has_published_nodes = db_select('node')
    ->condition('uid', $user->uid)
    ->condition('status', NODE_PUBLISHED)
    ->range(0, 1)->countQuery()->execute()->fetchField();
  if ($has_published_nodes)
    return TRUE;

  $has_published_comments = db_select('comment')
    ->condition('uid', $user->uid)
    ->condition('status', COMMENT_PUBLISHED)
    ->range(0, 1)->countQuery()->execute()->fetchField();
  if ($has_published_comments)
    return TRUE;

  // 3.

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'og_membership')
    ->propertyCondition('group_type', 'node')
    ->propertyCondition('etid', $user->uid)
    ->propertyCondition('entity_type', 'user')
    ->execute();

  if (!empty($result['og_membership'])) {
    $memberships = og_membership_load_multiple(array_keys($result['og_membership']));
    foreach ($memberships as $membership) {
      $user_roles_in_group = og_get_user_roles('node', $membership->gid, $user->uid, FALSE);
      if (in_array(OG_ADMINISTRATOR_ROLE, $user_roles_in_group))
        return TRUE;
    }
  }

  return FALSE;
}

/**
 * Implements hook_user_presave().
 */
function cluster_user_user_presave(&$edit, $account, $category) {
  if (!$account->is_new)
    return;

  if (cluster_user_is_mail_blocked_from_registering($account->mail, "user_presave, name: {$account->name}, IP: {$_SERVER['REMOTE_ADDR']}"))
    // Normally, this wouldn't happen, as there's also validation in the user_register form to show nice validation errors. This is just a last resort.
    die('Email address blocked. Please contact an administrator if you believe this is a mistake.');
}

function cluster_user_user_register_form_validate(&$form, &$form_state) {
  if (cluster_user_is_mail_blocked_from_registering($form_state['input']['mail'], "user_register_form_validate, name: {$form_state['input']['name']}, IP: {$_SERVER['REMOTE_ADDR']}"))
    form_set_error('mail', t("Email address blocked. Please contact an administrator if you believe this is a mistake."));
}

function cluster_user_is_mail_blocked_from_registering($mail, $context = 'unknown') {
  $whitelist = explode("\n", variable_get('cluster_user_registration_whitelist', ''));
  $whitelist = array_map('trim', $whitelist);
  $whitelist = array_map('strtolower', $whitelist);
  $whitelist = array_values(array_filter($whitelist));

  if (in_array(trim(strtolower($mail)), $whitelist))
    return FALSE; // it's whitelisted!

  $regex_blacklist = explode("\n", variable_get('cluster_user_registration_regex_blacklist', ''));
  foreach ($regex_blacklist as $regex) {
    $regex = trim($regex);
    if ($regex === '')
      continue;

    $match = preg_match($regex, $mail);
    if ($match === 1) {
      watchdog('cluster_user', 'Email %mail blocked using rule %regex (%context)', [
        '%regex' => $regex,
        '%mail' => $mail,
        '%context' => $context,
      ], WATCHDOG_CRITICAL);
      return TRUE;
    } elseif ($match === 0)
      continue;
    elseif ($match === FALSE) {
      watchdog('cluster_user', 'Error on regex: %regex', [
        '%regex' => $regex,
      ], WATCHDOG_ERROR);
      continue; // let it pass
    } else {
      watchdog('cluster_user', 'Unexpected result from preg_match() on regex %regex: %result', [
        '%regex' => $regex,
        '%result' => $match,
      ], WATCHDOG_ERROR);
      continue; // let it pass
    }
  }

  return FALSE;
}
